## Exercise 1.

How much is $2^{38}$?

Recall that Python supports the usual arithmetic operators like `+`, `-`, `*`, `/`, etc.

In [2]:
2**38

274877906944

In [4]:
1 == 1

True

In [5]:
1 = 1

SyntaxError: can't assign to literal (<ipython-input-5-4c0a01f26144>, line 1)

----

## Exercise 2.

The `help()` function prints documentation about other functions.

In [7]:
# what does this print?
help(help)

Help on _Helper in module site object:

class _Helper(__builtin__.object)
 |  Define the builtin 'help'.
 |  This is a wrapper around pydoc.help (with a twist).
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *args, **kwds)
 |  
 |  __repr__(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



Print the help text for other functions: what happens if you type `help(help)`?

----

## Exercise 3.

Define a function `greet(name)` with one parameter that prints "Hello" and then the given name.

Recall that:
- *indentation is significant in Python!*
- every statement that starts a block (e.g., `def`, `if`, etc.) *must end with a colon "`:`"*

In [11]:
def greet(name):
    print("Hello, " + name)
    
greet(42)

TypeError: cannot concatenate 'str' and 'int' objects

----

## Exercise 4.

Modify function `greet` above to print `"Welcome back!"` if `name` is the string `'BrainHack'`.

In [12]:
def greet(name):
    # how should you modify the code below?
    if name == 'BrainHack':
        print("Welcome back!")
    else:
        print("Hello {0}!".format(name))
    
greet('BrainHack')

Welcome back!


----

## Exercise 5.

What does the following cell output when evaluated for the first time?  And if you evaluate it a second time?

In [ ]:
import hello

----

## Exercise 6.

Write a function `avg()` that takes a list of numbers and returns their mean value.

In [13]:
def avg(L):
    return (sum(L) / len(L))

If your solution is correct, evaluating the following cell should produce `2` as output:

In [14]:
avg([1, 2, 3])

2

----

## Exercise 7.

Write a function `odd(L)` that takes a list of integers and returns a list of all the odd ones.

Recall that:
* the `%` operator is used for computing the remainder of integer division;
* the [`.append()`](https://docs.python.org/2/library/stdtypes.html?highlight=list.append#list.append) method is used to append an element to a list

In [15]:
def odd(L):
    result = []
    for x in L:
        if (x % 2) == 1:
            result.append(x)
    return result

If your solution is correct, evaluating the following cell should produce `[2]` as output:

In [16]:
odd([1,2,3])

[1, 3]

----

## Exercise 8.

Write a function `deviation(L, m)` that takes a list `L` of
numbers and a single value `m` returns a list with the 
absolute value of the difference $|x-m|$
for each element `x` of `L`.

In [17]:
def deviation(L, m):
    result = []
    for x in L:
        result.append(abs(x - m))
    return result

If your solution is correct, evaluating the following cell should produce `[1, 0, 1]` as output:

In [18]:
deviation([1,2,3], 2)

[1, 0, 1]

----

## Exercise 9.

Write a function `load_data(filename)` that reads a file
containing one integer number per line, and return a list of the
integer values.

Recall that functions `int()`, `float()`, `str()` are used to convert an object to integer, floating-point number, or string (respectively).

In [19]:
def load_data(filename):
    result = []
    with open(filename, 'r') as stream:
        # ...
        for line in stream:
            num = int(line)
            result.append(num)
    return result

If your solution is correct, evaluating the following cell should produce `[299850, 299740, 299900, 300070, 299930]` as output

In [20]:
load_data('values.txt')

[299850, 299740, 299900, 300070, 299930]

----

## Exercise 10.

Write a function `wordcount(filename)` that reads a text
file and returns a dictionary, mapping words into occurrences
(disregarding case) of that word in the text.

You might find useful:
* the `with open(...)` pattern for reading lines of a file;
* the [`.split()`](http://www.pythonforbeginners.com/dictionary/python-split) method of Python strings, to break a string at every occurrence of a substring or whitespace
* the [`.lower()`](https://docs.python.org/2/library/stdtypes.html?highlight=str.lower#str.lower) method of Python strings, to convert a string to lowercase

In [ ]:
# insert code here and evaluate cell

If your solution is correct, evaluating the following cell should produce `(1, 2, 3)` as output.

In [ ]:
wc = wordcount('lipsum.txt')

print(wc['bacon'], wc['filet'], wc['ham'])

----

## Exercise 11.

Try loading file `values2.txt` with the `load_data()` function from Exercise 9. -- what exception does Python raise?

Edit the `load_data()` function so that it *ignores* any line that does not contain an integer number.

In [ ]:
# insert code here and evaluate cell

If your solution is correct, evaluating the following cell should produce `[299850, 300070, 299930]` as output:

In [ ]:
load_data2('values2.txt')

**Note:** There is a way to write `load_data2()` so that it has exactly the same output of `load_data()`, i.e. minimize the number of rejected input lines.  Bonus points if you manage to do that.