## Exercise 1.A

How much is $2^{144}$?

Recall that Python supports the usual arithmetic operators like `+`, `-`, `*`, `/`, etc.

----

## Exercise 2.A

The `help()` function prints documentation about other functions.

In [2]:
# what this print?
help(abs)

Help on built-in function abs in module __builtin__:

abs(...)
    abs(number) -> number
    
    Return the absolute value of the argument.



Print the help text for other functions: what happens if you type `help(help)`?

----

## Exercise 2.B

Define a function `greet(name)` with one parameter that prints "Hello" and then the given name.

Recall that:
- *indentation is significant in Python!*
- every statement that starts a block (e.g., `def`, `if`, etc.) *must end with a colon "`:`"*

In [4]:
# insert code here and then evaluate the cell

----

## Exercise 2.C

Modify function `greet` above to print `"Welcome back!"` if `name` is the string `'Python'`.

In [1]:
def greet(name):
    # how should you modify the code below?
    print("Hello {0}!".format(name))
    
greet('Python')

Hello Python!


----

## Exercise 5.

What does the following cell output when evaluated for the first time?  And if you evaluate it a second time?

In [6]:
import hello

----

## Exercise 3.A

Write a function `avg()` that takes a list of numbers and returns their mean value.

In [10]:
def avg(nums):
    return sum(nums) / len(nums)

If your solution is correct, evaluating the following cell should produce `2` as output:

In [11]:
avg([1, 2, 3])

2

----

## Exercise 3.B

Write a function `odd(L)` that takes a list of integers and returns a list of all the odd ones.

Recall that:
* the `%` operator is used for computing the remainder of integer division;
* the [`.append()`](https://docs.python.org/2/library/stdtypes.html?highlight=list.append#list.append) method is used to append an element to a list

In [13]:
def odd(L):
    result = []
    for x in L:
        if (x % 2) == 0:
            result.append(x)
    return result

If your solution is correct, evaluating the following cell should produce `[2]` as output:

In [14]:
odd([1,2,3])

[2]

----

## Exercise 3.C

Write a function `deviation(L, m)` that takes a list `L` of
numbers and a single value `m` returns a list with the 
absolute value of the difference $|x-m|$
for each element `x` of `L`.

In [15]:
def deviation(L, m):
    result = []
    for x in L:
        result.append(abs(x-m))
    return result

If your solution is correct, evaluating the following cell should produce `[1, 0, 1]` as output:

In [16]:
deviation([1,2,3], 2)

[1, 0, 1]

---

## Exercise 3.D

Write a function `plotfn(x,f)` that takes two arguments: a list of numbers `xs` and a mathematical function `f` (one single numerical argument, returns a number) and plots the graph of `f` on the domain `xs`.

----

## Exercise 4.A

Write a function `load_data(filename)` that reads a file
containing one integer number per line, and return a list of the
integer values.

Recall that functions `int()`, `float()`, `str()` are used to convert an object to integer, floating-point number, or string (respectively).

In [17]:
def load_data(filename):
    result = []
    with open(filename) as stream:
        for line in stream:
            num = int(line)
            result.append(num)
    return result

If your solution is correct, evaluating the following cell should produce `[299850, 299740, 299900, 300070, 299930]` as output

In [32]:
load_data('values.txt')

[299850, 299740, 299900, 300070, 299930]

----

## Exercise 5.A

Try loading file `values2.txt` with the `load_data()` function from Exercise 4.A -- what exception does Python raise?

Edit the `load_data()` function so that it *ignores* any line that does not contain an integer number.

In [33]:
def load_data2(filename):
    result = []
    with open(filename) as stream:
        for line in stream:
            try:
                num = int(line)
            except ValueError:
                # ignore line
                continue
            result.append(num)
    return result

If your solution is correct, evaluating the following cell should produce `[299850, 300070, 299930]` as output:

In [34]:
load_data2('values2.txt')

[299850, 300070, 299930]

**Note:** There is a way to write `load_data2()` so that it has exactly the same output of `load_data()`, i.e. minimize the number of rejected input lines.  Bonus points if you manage to do that.

----

## Exercise 6.A

Write a function `wordcount(filename)` that reads a text
file and returns a dictionary, mapping words into occurrences
(disregarding case) of that word in the text.

You might find useful:
* the `with open(...)` pattern for reading lines of a file;
* the [`.split()`](http://www.pythonforbeginners.com/dictionary/python-split) method of Python strings, to break a string at every occurrence of a substring or whitespace
* the [`.lower()`](https://docs.python.org/2/library/stdtypes.html?highlight=str.lower#str.lower) method of Python strings, to convert a string to lowercase

In [27]:
def wordcount(filename):
    wc = {}
    with open(filename, 'r') as stream:
        for line in stream:
            words = line.split()
            for word in words:
                word = word.lower()
                if word not in wc:
                    wc[word] = 1
                else:
                    wc[word] += 1
    return wc

If your solution is correct, evaluating the following cell should produce `(1, 2, 3)` as output.

In [31]:
wc = wordcount('lipsum.txt')

print(wc['bacon'], wc['filet'], wc['ham'])

(1, 2, 3)
